# Welcome to Jekyll!

title: Charlas Eryx
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: eryxcoop

# Build settings
remote_theme: pmarsceill/just-the-docs
search_enabled: true
plugins:
  - jekyll-feed

aux_links_new_tab: true